changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Highlights
      labels:
        - feature
        - enhancement
        - launch
    - title: Install & Packaging
      labels:
        - release
        - packaging
        - docs
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Internal
      labels:
        - chore
        - refactor
        - test
